export const REQUEST_POKEMONS = 'REQUEST_POKEMONS';
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS';
export const REQUEST_POKEMON = 'REQUEST_POKEMON';
export const RECEIVE_POKEMON = 'RECEIVE_POKEMON';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

